### PR TITLE
Support for URLs in lists

### PR DESCRIPTION
**Pull request by lightsprint09**

### CODE REVIEW

**Review by heckj — APPROVED** [review]
Look good to me - GitHub is reporting that it has conflicts that can't be merged (like the other PRs), but if you can rebase or squash and merge, have at!

**Comment by heckj** [comment]
Hey Lucas - sorry to tack this only a merged/closed PR, but didn't have another way to get ahold of you (I don't see you on the public Automerge discord). You have other bits and pieces you think are pending from your porting/migration work? I was thinking I'd like to get a test in that validates against the interop document we just merged into the automerge-core, and then cut another release - mostly to get the time discrepancy/interpretation bugfix released, but if there's more you're thinking about near time, I'm happy to wait a bit.

**Comment by lightsprint09** [comment]
Trying to fly under the radar ;) I have a full time software engineering job and most of the time I don't feel like coding during the evenings anymore. If there is something important just @ me here at GitHub and I am happy to help.

I successfully migrated my app to the new auto merge. It is much faster now and works fine 👍🏾

**Comment by heckj** [comment]
No worries, thanks - I won't hold up another release cut

**Pull request merged**
