### PR TITLE
Adds support to encode & decode Foundation.URL

### PR DESCRIPTION
**Pull request by lightsprint09**

### CODE REVIEW

**Review by heckj — APPROVED** [review]
Hey Lucas! Looks good - thanks for the submission.

I admit I didn't check explicitly, but I thought URL was already codable and that it's default encoding would work to do what you're after. Is it not?

**Comment by lightsprint09** [comment]
No worries, would have guessed the same. I am currently migrating from the old automerge to the new one and discovered it did not work as expected.

**Comment by heckj** [comment]
yeah, just double checked and URL is definitely Codable - I'm guessing this was because you wanted a specific in-automerge-schema representation for it? That plain string?

When I coded it (prior to this PR) and dumped the schema, I got:
```
      "url" : {
        {
        "relative" :String(https://automerge.org/)
        }
      }
```

**Comment by lightsprint09** [comment]
Right, I would expect. This is how JSONDecoder/Encoder handle an URL

```
"url" : String(https://automerge.org/)
```

**Pull request merged**
